remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Science Robotics"
repository_url: "https://github.com/ac-rad/organa"
show_arxiv: true
arxiv_url: "insert paper link"
description: Insert authors
